version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=portfolio.settings.prod
    command: gunicorn portfolio.wsgi --bind 0.0.0.0:8000
