# Generated by Django 2.2 on 2020-03-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='message_content',
            field=models.TextField(default='empty message'),
        ),
    ]
