# Generated by Django 2.2 on 2020-04-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200328_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='message_content',
            field=models.TextField(verbose_name='Message details'),
        ),
    ]
